### ISSUE TITLE
Refactor Geometric Moves

### ISSUE THREAD

**Issue by V-Wong** [V-Wong/CubeSimRS#43]
The implementation of [geometrics moves](https://github.com/V-Wong/CubeSim2/blob/main/src/geometric_cube/moves.rs) currently features a lot of duplicate code. This was originally done as a temporary solution to support arbitrary sized cubes. A more elegant solution with less duplicate code would be preferred here.

**Comment by stanleydesu** [comment]
Solved by https://github.com/V-Wong/CubeSimRS/pull/57 ?
